---
- name: Create a new user
  user:
    name: "{{user}}"
    shell: /bin/bash
    state: present
- name: Add user to sudo group
  user:
    name: "{{user}}"
    groups: wheel
    append: yes
- name: Allow passwordless sudo for user
  lineinfile:
    path: /etc/sudoers.d/{{user}}
    state: present
    line: '{{user}} ALL=(ALL) NOPASSWD:ALL'
    create: yes
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
- name: Set authorized keys for user
  authorized_key:
    user: "{{user}}"
    state: present
    key: https://raw.githubusercontent.com/taiwaiho624/Workflow/refs/heads/master/keys/michael.key