---
- name: Main Playbook
  hosts: localhost
  become: yes
  vars:
    - user: 'test'
    - dotfiles_repo: 'https://github.com/taiwaiho624/Workflow.git'
  tasks:
    - name: "Set up new user"
      import_tasks: create_user.yml
    - name: "Disable password auth"
      import_tasks: disable_pw_auth.yml
    - name: "install system dependencies"
      import_tasks: install_dependencies.yml
    - name: "Set up dot files"
      import_tasks: setup_dotfiles.yml
